services:
  inference:
    build: ./inference
    container_name: inference_service
    ports:
      - "8000:8000"
    networks:
      - app_network

  ui:
    build: ./ui
    container_name: ui_service
    ports:
      - "7860:7860"
    environment:
      BACKEND_URL: "http://inference:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
